import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getAdvertisements from "@/lib/actions/getAdvertisements";
import { AdvertisementState } from "@/stores/advertisement.store";
import { AdvertisementStoreProvider } from "@/providers/advertisement.store.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const advertisements = await getAdvertisements();
  const initialState: AdvertisementState = {
    advertisements,
    nextAdvertisment: 0,
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdvertisementStoreProvider initialState={initialState}>
          {children}
        </AdvertisementStoreProvider>
      </body>
    </html>
  );
}
